#!/usr/bin/env sh
vim="$HOME/.vim"
repos="https://github.com/jimzhan/.vim"

log() {
    printf '\033[0;34m%s\033[0m\n' "${1}"
}

info() {
    printf "\e[34m[I]\e[0m ${1}\n"
}

error() {
    printf "\e[31m[✘]\e[0m ${1}\n"
}

success() {
    printf "\e[32m[✔]\e[0m ${1}\n"
}

if [ ! -d $vim ]; then
    info "Setting up Vim..."
    git clone $repos $vim
    success "Vim fetched, starting up..."
else
    cd $vim && git pull -v
    success "Vim is now updated"
fi

# backup/unlink existing vimrc
# ------------------------------
if [ -f $HOME/.vimrc ]; then
    mv $HOME/.vimrc $HOME/.vimrc.bak
    info ".vimrc    =>  .vimrc.bak"
fi

if [ -L $HOME/.vimrc ]; then
    unlink $HOME/.vimrc
    info "existing .vimrc unlinked"
fi

# backup/unlink existing gvimrc
# ------------------------------
if [ -f $HOME/.gvimrc ]; then
    mv $HOME/.gvimrc $HOME/.gvimrc.bak
    info ".gvimrc   =>  .gvimrc.bak"
fi

if [ -L $HOME/.gvimrc ]; then
    unlink $HOME/.gvimrc
    info "existing .gvimrc unlinked"
fi

ln -s $vim/vimrc  $HOME/.vimrc
ln -s $vim/gvimrc $HOME/.gvimrc
